[package]
name = "coriscos"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.40"
config = { version = "0.15.11", default-features = false, features = ["toml"] }
image = "0.24.7"
rand = "0.9"
rayon = "1.8.0"
serde = { version = "1.0.219", features = ["derive"] }
